import colors from "@/assets/colors.js";

export default {
    name: 'landos',
    component: 'ConnectionCircles',
    content: {
        en: {
            title: 'LandOS',
            connectMessageBgColor: colors.backgroundLightTranslucent,
            connectMessageTextColor: colors.textDark,
            connectButtonBgColor: colors.secondary,
            connectButtonTextColor: colors.textDark,
            circlesClosedDiameter: "30vh",
            circlesOpenDiameter: "60vh",
            circles: [
                {
                    id: "landOsLogo",
                    position: "center-middle",
                    img: "/img/landos_logo_glow.png",
                    textColor: colors.secondary,
                    title: "Unified Terrain Management Platform",
                    activeOnStart: true
                },
                {
                    id: "optimizationEngine",
                    position: "top-middle",
                    title: "Optimization Engine",
                    text: "The Optimization Engine evaluates what should happen next. Using the terrain model built from analytics, it compares the current state of the site with the desired one, simulates options, and publishes the operational parameters needed to move the biorome toward its goals.",
                    buttonText: "Connect",
                    connectionText: "Optimization outputs the next best actions for the terrain.",
                    messagePosition: "center-right",
                    endpointOverlap: 20,
                    target: "operationsEngine",
                    arrowColor: colors.primary,
                    borderColor: colors.primary,
                    borderWidth: 2,
                    bgColor: colors.backgroundDark,
                    textColor: colors.primary,
                },
                {
                    id: "operationsEngine",
                    position: "bottom-right",
                    title: "Operations Engine",
                    text: "The Operations Engine coordinates execution on the ground. It turns parameters into actions across robotic modules, infrastructure, workflows, and field teams, and it keeps the system moving whether the work is fully automated, human-assisted, or a combination of both.",
                    buttonText: "Connect",
                    connectionText: "Operations reports field reality and execution results back into the loop.",
                    messagePosition: "bottom-middle",
                    endpointOverlap: 20,
                    target: "dataEngine",
                    arrowColor: colors.primary,
                    borderColor: colors.primary,
                    borderWidth: 2,
                    bgColor: colors.backgroundDark,
                    textColor: colors.primary,
                },
                {
                    id: "dataEngine",
                    position: "bottom-left",
                    title: "Analytics Engine",
                    text: "The Analytics Engine helps understand what is happening on the land. It gathers, normalizes, and interprets data from sensors, terrain history, environmental conditions, market signals, and expert inputs so the rest of the system can operate on a grounded view of reality.",
                    buttonText: "Connect",
                    connectionText: "Analytics prepares the terrain picture that optimization uses to decide.",
                    messagePosition: "center-left",
                    target: "optimizationEngine",
                    arrowColor: colors.primary,
                    borderColor: colors.primary,
                    borderWidth: 2,
                    bgColor: colors.backgroundDark,
                    textColor: colors.primary,
                }
            ]
        },
        es: {
            title: 'LandOS',
            connectMessageBgColor: colors.backgroundLightTranslucent,
            connectMessageTextColor: colors.textDark,
            connectButtonBgColor: colors.secondary,
            connectButtonTextColor: colors.textDark,
            circlesClosedDiameter: "30vh",
            circlesOpenDiameter: "60vh",
            circles: [
                {
                    id: "landOsLogo",
                    position: "center-bottom",
                    img: "/img/landos_logo_glow.png",
                    textColor: colors.secondary,
                    title: "Plataforma Unificada de Gestión del Terreno",
                    activeOnStart: true
                },
                {
                    id: "optimizationEngine",
                    position: "top-middle",
                    title: "Motor de Optimización",
                    text: "El Motor de Optimización evalúa qué debe ocurrir a continuación. Utilizando el modelo del terreno construido a partir de la analítica, compara el estado actual del sitio con el estado deseado, simula opciones y publica los parámetros operativos necesarios para mover el bioroma hacia sus objetivos.",
                    buttonText: "Conectar",
                    connectionText: "La optimización produce las siguientes mejores acciones para el terreno.",
                    messagePosition: "center-right",
                    endpointOverlap: 20,
                    target: "operationsEngine",
                    arrowColor: colors.primary,
                    borderColor: colors.primary,
                    borderWidth: 2,
                    bgColor: colors.backgroundDark,
                    textColor: colors.primary,
                },
                {
                    id: "operationsEngine",
                    position: "bottom-right",
                    title: "Motor de Operaciones",
                    text: "El Motor de Operaciones coordina la ejecución sobre el terreno. Convierte parámetros en acciones a través de módulos robóticos, infraestructura, flujos de trabajo y equipos de campo, y mantiene el sistema en movimiento tanto si el trabajo es totalmente automatizado como si es asistido por personas o una combinación de ambos.",
                    buttonText: "Conectar",
                    connectionText: "Operaciones devuelve al bucle la realidad de campo y los resultados de la ejecución.",
                    messagePosition: "bottom-middle",
                    endpointOverlap: 20,
                    target: "dataEngine",
                    arrowColor: colors.primary,
                    borderColor: colors.primary,
                    borderWidth: 2,
                    bgColor: colors.backgroundDark,
                    textColor: colors.primary,
                },
                {
                    id: "dataEngine",
                    position: "bottom-left",
                    title: "Motor de Analítica",
                    text: "El Motor de Analítica ayuda a entender qué está ocurriendo sobre el terreno. Recoge, normaliza e interpreta datos procedentes de sensores, historial del terreno, condiciones ambientales, señales de mercado e inputs expertos para que el resto del sistema opere sobre una visión fundamentada de la realidad.",
                    buttonText: "Conectar",
                    connectionText: "La analítica prepara la imagen del terreno que la optimización utiliza para decidir.",
                    messagePosition: "center-left",
                    target: "optimizationEngine",
                    arrowColor: colors.primary,
                    borderColor: colors.primary,
                    borderWidth: 2,
                    bgColor: colors.backgroundDark,
                    textColor: colors.primary,
                }
            ]
        }
    }
};
