import colors from "@/assets/colors.js";

export default {
    name: 'team',
    component: 'ActionColumns',
    content: {
        en: {
            title: 'Our Team',
            general: {
                slideTitle: 'Team',
                slideTitleColor: colors.primary,
                slideIntro: 'The humans behind the tech',
                slideIntroColor: colors.secondary,
                columnsPerRow: 2
            },
            columns: [
                {
                    columnIconImg: "/img/reuven.jpeg",
                    columnTitle: "Reuven Farchi – President & CTO, Co-founder",
                    columnText: "Solutions architect raised in a farming family, with deep expertise in SaaS, AI, IoT, and geospatial systems. Co-founded Agrobots to reconnect technology and land.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/reuven-farchi-44764221/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.secondary,
                    borderColor: colors.secondary,
                },
                {
                    columnIconImg: "/img/mariajose.jpeg",
                    columnTitle: "María José Azurdia – CEO & CFO, Co-founder",
                    columnText: "Agribusiness leader, farmer, and women’s rights activist in Guatemala. Brings hands-on operations, public/private development experience, and project innovation leadership.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/maria-jose-azurdia-poole-506a907/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.secondary,
                    borderColor: colors.secondary,
                },
                {
                    columnIconImg: "/img/carolina.jpeg",
                    columnTitle: "Carolina Salazar – Chief Technology Strategist",
                    columnText: "Chief Technology Strategist with 15+ years in emerging tech, AI, and sustainability. Expert in strategy for technology-driven social impact.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/carohedman/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.primary,
                    borderColor: colors.primary,
                },
                {
                    columnIconImg: "/img/daniel.jpeg",
                    columnTitle: "Daniel Hedman – Marketing & Analytics Lead",
                    columnText: "Marketing & Analytics Lead. 10 years of experience driving digital growth and performance marketing in high-impact sectors.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/hedman/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.primary,
                    borderColor: colors.primary,
                },
                {
                    columnIconImg: "/img/polett.jpeg",
                    columnTitle: "Polett Sarmiento – Client Relations & Tenders",
                    columnText: "Specialist in content strategy, public-private bids, and institutional partnerships.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/ana-polett-sarmiento-reyes-20779944/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.primary,
                    borderColor: colors.primary,
                },
                {
                    columnIconImg: "/img/imanol.jpeg",
                    columnTitle: "Imanol Lizartza – Planning & Partnerships",
                    columnText: "15+ years of experience in regional development, sustainability transitions, and collaborative networks.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/imanol-lizartza/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.primary,
                    borderColor: colors.primary,
                }
            ]
        },
        es: {
            title: 'El Equipo',
            general: {
                slideTitle: 'Equipo',
                slideTitleColor: colors.primary,
                slideIntro: 'Las personas detrás de la tecnología',
                slideIntroColor: colors.secondary,
                columnsPerRow: 2,
            },
            columns: [
                {
                    columnIconImg: "/img/reuven.jpeg",
                    columnTitle: "Reuven Farchi – Presidente y CTO, Cofundador",
                    columnText: "Arquitecto de soluciones criado en familia agrícola, con experiencia en SaaS, IA, IoT y sistemas geoespaciales. Cofundador de Agrobots para reconectar tecnología y tierra.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/reuven-farchi-44764221/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.secondary,
                    borderColor: colors.secondary,
                },
                {
                    columnIconImg: "/img/mariajose.jpeg",
                    columnTitle: "María José Azurdia – CEO y CFO, Cofundadora",
                    columnText: "Líder agroempresarial, agricultora y activista por los derechos de las mujeres en Guatemala. Experta en operaciones y desarrollo público-privado, y liderazgo en innovación.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/maria-jose-azurdia-poole-506a907/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.secondary,
                    borderColor: colors.secondary,
                },
                {
                    columnIconImg: "/img/carolina.jpeg",
                    columnTitle: "Carolina Salazar – Líder de Estrategia Tecnólogica",
                    columnText: "Chief Technology Strategist con más de 15 años en tecnologías emergentes, IA y sostenibilidad. Especialista en estrategia para impacto social basado en tecnología.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/carohedman/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.primary,
                    borderColor: colors.primary,
                },
                {
                    columnIconImg: "/img/daniel.jpeg",
                    columnTitle: "Daniel Hedman – Líder de Marketing y Analítica",
                    columnText: "10 años de experiencia impulsando crecimiento digital y marketing de alto impacto.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/hedman/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.primary,
                    borderColor: colors.primary,
                },
                {
                    columnIconImg: "/img/polett.jpeg",
                    columnTitle: "Polett Sarmiento – Relaciones y Licitaciones",
                    columnText: "Especialista en estrategia de contenidos, licitaciones público-privadas y alianzas institucionales.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/ana-polett-sarmiento-reyes-20779944/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.primary,
                    borderColor: colors.primary,
                },
                {
                    columnIconImg: "/img/imanol.jpeg",
                    columnTitle: "Imanol Lizartza – Planificación y Alianzas",
                    columnText: "Más de 15 años de experiencia en desarrollo regional, sostenibilidad y redes colaborativas.",
                    buttonText: "LinkedIn",
                    buttonLink: "https://www.linkedin.com/in/imanol-lizartza/",
                    buttonBgColor: colors.accent,
                    buttonTextColor: colors.textDark,
                    buttonBorderColor: colors.accent,
                    columnsBgColor: colors.backgroundDark,
                    textColor: colors.primary,
                    borderColor: colors.primary,
                }
            ]
        }
    }
}
;